package de.fhkiel.pepper.cms_lib.apps;

import java.util.HashMap;

/**
 * Interface for an app to implement. Allows callbacks generated by cms system.
 */
public interface PepperAppInterface {

    /**
     * Callback, {@link PepperCMSControllerInterface} uses, if {@link PepperApp}s are loaded.
     *
     * @param apps List of loaded available {@link PepperApp}s
     */
    void onPepperAppsLoaded(HashMap<String, PepperApp> apps, boolean isRemote);

    /**
     * Called, if app will be started
     * @param app   {@link PepperApp} that is started
     */
    void onAppStarted(PepperApp app);

    /**
     * Called if an update for a {@link PepperApp} is available
     * @param app   {@link PepperApp} update is available for.
     */
    void onAppUpdateAvailable(PepperApp app);

    /**
     * Called if app update starts
     * @param app   {@link PepperApp} app updated is started for.
     */
    void onAppUpdate(PepperApp app);

    /**
     * Called if {@link PepperApp} is updated.
     * @param app   {@link PepperApp} that is updated.
     */
    void onAppUpdated(PepperApp app);
}
